AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - Gemfile
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.2
BlockComments:
  Enabled: false
Documentation:
  Enabled: false
LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
